### PR TITLE
Added CI. The library is automatically built for windows, linux, macos.

### PR DESCRIPTION
**Pull request by ksv87**
If you need to create a release (GitHub Action automatically creates a release and attaches artifacts),
after you have pushed the changes, you need to add a tag and send it:
git tag v1.0.0
git push origin --tags

PS: the script is taken as a basis https://github.com/cristianadam/HelloWorld

### CODE REVIEW

**Comment by ksv87** [comment]
in the readme, you will need to fix the repository links in the icons in the first line

**Comment by embeddedmz** [comment]
Thank you for your contribution. I updated the URL in Readme but I don't know if it's correct. Otherwise, I don't know how the CI works.

**Comment by ksv87** [comment]
You need execut 3 command from your console
git pull
git tag v1.0.0
git push origin --tags

**Comment by ksv87** [comment]
When you push the changes there is just a build, the artifacts are available on the gitaction tab. If you push the changes together with the tag that starts on v (v1.0.0, etc.), the release is also published.

**Pull request merged**
